apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    {{ if .Values.service.targetPort }}
    targetPort: {{ .Values.service.targetPort }}
    {{ else }}
    targetPort: {{ .Values.service.port }}
    {{ end }}
  selector:
    app: {{ .Values.app.name }}
  type: {{ .Values.service.type }}