name: "TechTrends - Package with Docker"
# github action on every push on main branch
on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            # mmansoornano/udacity-techtrends
            ghcr.io/mmansoornano/udacity-techtrends
          # tag-custom: latest
          # tag-semver: |
          #   {{raw}}
         # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=v1.0.${{ github.run_number }},priority=1000
            type=ref,event=branch
            type=sha
            type=raw,value=latest
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          
          file: ./project/techtrends/Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          # builder: ${{ steps.buildx.outputs.name }}
          # labels: |
          #   org.opencontainers.image.authors=${{ github.repository_owner }}
          #   org.opencontainers.image.created=${{ env.BUILD_DATE }}
          #   org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          #   org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          #   org.opencontainers.image.revision=${{ github.sha }}
          #   org.opencontainers.image.source=https://github.com/${{ github.repository }}
          #   org.opencontainers.image.version=${{ env.BUILD_VER }}
          #   # tags: mmansoornano/udacity-techtrends:latest
          # tags: | 
          #   ${{ env.IMAGE }}:latest
          #   ${{ env.IMAGE }}:${{ env.GIT_REF }}
          #   ${{ env.IMAGE }}:${{ env.GIT_SHA }}
          #   ${{ env.IMAGE }}:${{ env.BUILD_VER }}
          # load: true
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache
      # - run: docker push ${{ env.IMAGE }}:latest
          #${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}